import json
from pathlib import Path
root=Path('benchmark/blind');manifest=json.loads((root/'manifest.json').read_text())
page='''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>EDITMAP / Blind validation</title><style>body{background:#141618;color:#dce0e2;font:15px system-ui;margin:24px}p{max-width:1000px;line-height:1.6;color:#a9b5bd}.grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(340px,1fr));gap:16px}article{background:#202528;padding:16px;border:1px solid #3d464c}img{width:100%;height:auto}label{display:flex;align-items:center;justify-content:space-between;margin:10px 0;gap:8px}select,button{background:#30383d;color:white;border:1px solid #73818a;padding:9px}select{max-width:65%}header{position:sticky;top:0;padding:12px;background:#141618;z-index:1}button:disabled{opacity:.4}.checks{justify-content:flex-start}details{max-width:1000px;margin:15px 0}li{margin:8px 0}</style><h1>EDITMAP / Blind validation</h1><p>40 new shots. No model predictions or preselected labels. Label only the displayed frame, choose Unknown when needed, and confirm each entry. The model will receive the exact same images after this review.</p><details open><summary>Framing definitions</summary><ul><li>ECS: face part or tiny detail fills the frame.</li><li>CS: head and shoulders.</li><li>MS: substantial torso; body cropped. A seated group can be MS.</li><li>FS: essentially head to toe, with the main subject prominent.</li><li>LS: surroundings dominate; people relatively small.</li><li>Composition counts the subjects of the shot, not every background passerby. A group is not automatically FS.</li><li>Text cards: content Text / title card, size Not applicable. Object/detail can still have a size; composition Unknown.</li></ul></details><header><b id="count"></b> <button id="export" disabled>Export blind review</button></header><div class="grid"></div><script>
const manifest=MANIFEST;let review={};const storage='editmap-'+manifest.id;try{review=JSON.parse(localStorage.getItem(storage)||'{}')}catch{}const choices={size:['ECS','CS','MS','FS','LS','Unknown','Not applicable'],composition:['Single person','Two-shot','Group','Unknown'],content:['People','Object / detail','Text / title card','Other','Unknown']};
function status(){const n=manifest.shots.filter(s=>review[s.index]?.confirmed).length;document.querySelector('#count').textContent=`${n}/40 confirmed`;document.querySelector('#export').disabled=n!==40;try{localStorage.setItem(storage,JSON.stringify(review))}catch{}}
for(const shot of manifest.shots){const id=shot.index,values=review[id]||{size:'',composition:'',content:'',uncertain:false,confirmed:false};review[id]=values;const card=document.createElement('article');const image=document.createElement('img');image.src=shot.image;image.alt=`Shot ${id}`;card.append(image);const title=document.createElement('h3');title.textContent=`Shot ${id} · ${shot.start}`;card.append(title);const controls={};const check=document.createElement('input');check.type='checkbox';check.checked=values.confirmed;
function changed(){values.confirmed=false;check.checked=false;check.disabled=!values.size||!values.composition||!values.content;status()}
for(const [field,options] of Object.entries(choices)){const label=document.createElement('label');label.textContent=field;const select=document.createElement('select');select.setAttribute('aria-label',`Shot ${id} ${field}`);for(const v of ['',...options]){const o=document.createElement('option');o.value=v;o.textContent=v||'Choose…';select.append(o)}select.value=values[field];controls[field]=select;select.onchange=()=>{const wasText=values.content==='Text / title card';values[field]=select.value;if(field==='content'&&wasText&&values.content!=='Text / title card'){values.size='';controls.size.value='';}if(values.content==='Text / title card'){values.size='Not applicable';values.composition='Unknown';controls.size.value=values.size;controls.composition.value=values.composition;}controls.size.disabled=values.content==='Text / title card';changed()};label.append(select);card.append(label)}controls.size.disabled=values.content==='Text / title card';
const uncertain=document.createElement('input');uncertain.type='checkbox';uncertain.checked=values.uncertain;uncertain.onchange=()=>{values.uncertain=uncertain.checked;changed()};const ul=document.createElement('label');ul.className='checks';ul.append(uncertain,'Uncertain framing');card.append(ul);check.disabled=!values.size||!values.composition||!values.content;check.onchange=()=>{values.confirmed=check.checked;status()};const cl=document.createElement('label');cl.className='checks';cl.append(check,'Reviewed and confirmed');card.append(cl);document.querySelector('.grid').append(card)}status();
document.querySelector('#export').onclick=()=>{const result={schemaVersion:3,validationId:manifest.id,shots:manifest.shots,referenceLabels:review};const url=URL.createObjectURL(new Blob([JSON.stringify(result,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='editmap-blind-review.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
</script></html>'''
# Do not embed the frozen prompt or predictions in the review interface.
public={k:v for k,v in manifest.items() if k in ['id','shots']};(root/'index.html').write_text(page.replace('MANIFEST',json.dumps(public)))
