import json,statistics,html
from pathlib import Path
root=Path('benchmark');review=json.loads(Path('/Users/indievision/Downloads/editmap-model-review.json').read_text());q=json.loads((root/'qwen-results.json').read_text());labels=review['referenceLabels'];classes=['ECS','CS','MS','FS','LS'];v={r['index']:r for r in review['results']};scored=[r for r in q['results'] if labels.get(str(r['index'])) in classes]
summary={'scored':len(scored),'videomaeCorrect':sum(v[r['index']]['prediction']==labels[str(r['index'])] for r in scored),'qwenCorrect':sum(r['prediction']==labels[str(r['index'])] for r in scored),'qwenMedianSeconds':statistics.median(r['seconds'] for r in q['results']),'qwenTotalSeconds':sum(r['seconds'] for r in q['results']),'qwenLoadSeconds':sum(r['loadSeconds'] for r in q['results']),'classes':{c:{'count':sum(labels[str(r['index'])]==c for r in scored),'correct':sum(labels[str(r['index'])]==c and r['prediction']==c for r in scored)} for c in classes}}
(root/'comparison-summary.json').write_text(json.dumps(summary,indent=2))
parts=['<!doctype html><html lang="en"><meta charset="utf-8"><title>EDITMAP model comparison</title><style>body{background:#141618;color:#dce0e2;font:15px system-ui;margin:28px}p{max-width:1000px;line-height:1.6;color:#aab6bd}table{border-collapse:collapse;width:100%}td,th{padding:12px;text-align:left;border-bottom:1px solid #394147}img{width:160px;aspect-ratio:4/3} .yes{color:#9cc8a0}.no{color:#e0a092}</style><h1>EDITMAP / Model comparison</h1>']
parts.append(f'<p>Reference-label agreement on {len(scored)} scored shots: <b>VideoMAE {summary["videomaeCorrect"]}/{len(scored)} · Qwen {summary["qwenCorrect"]}/{len(scored)}</b>. Mixed/unclear and unreviewed cases are excluded. Qwen median request time: {summary["qwenMedianSeconds"]:.2f}s.</p>')
parts.append('<p>Qwen3-VL 4B Q4_K_M judged the same low-resolution midpoint images used in your review, restored to 4:3. VideoMAE judged sixteen frames. This is a pipeline comparison, not a controlled architecture benchmark. Human labels were not included in model prompts. Text/object predictions have no separate reference labels yet.</p><table><tr><th>Shot</th><th>Review frame</th><th>Your label</th><th>VideoMAE</th><th>Qwen</th><th>Qwen content</th></tr>')
for r in q['results']:
 i=r['index'];y=labels.get(str(i),'Unreviewed');vp=v[i]['prediction'];qp=r['prediction'];color=lambda p:'yes' if p==y else 'no' if y in classes else ''
 parts.append(f'<tr><td>{i}</td><td><img src="shot-{i}.jpg" alt="Shot {i}"></td><td>{html.escape(y)}</td><td class="{color(vp)}">{html.escape(vp)}</td><td class="{color(qp)}">{html.escape(qp)}</td><td>{html.escape(r["content"] or "Unknown")}</td></tr>')
parts.append('</table></html>');(root/'comparison.html').write_text(''.join(parts));print(json.dumps(summary,indent=2))
