import json,statistics
from pathlib import Path
root=Path('benchmark');data=json.loads((root/'qwen-v2-results.json').read_text());old=json.loads(Path('/Users/indievision/Downloads/editmap-model-review.json').read_text());refs=old['referenceLabels'];valid=['ECS','CS','MS','FS','LS'];scored=[r for r in data['results'] if refs.get(str(r['index'])) in valid];correct=sum(r['prediction']==refs[str(r['index'])] for r in scored)
summary={'matchesOriginalLabels':correct,'originalScored':len(scored),'medianSeconds':statistics.median(r['seconds'] for r in data['results']),'uncertainCount':sum(r['uncertain'] is True for r in data['results'])};(root/'qwen-v2-summary.json').write_text(json.dumps(summary,indent=2))
page='''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>EDITMAP / Revised model review</title><style>body{background:#141618;color:#dce0e2;font:14px system-ui;margin:24px}p{max-width:1000px;color:#a5b1b8;line-height:1.6}.grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(310px,1fr));gap:16px}article{background:#202528;padding:15px;border:1px solid #414a50}img{width:100%;aspect-ratio:4/3}label{display:block;margin:8px 0}select,button{background:#30383d;color:white;border:1px solid #65717a;padding:8px}select{float:right;max-width:65%}header{position:sticky;top:0;background:#141618;padding:12px;z-index:1}small{color:#b4bec4}</style><h1>EDITMAP / Revised classification review</h1><p>Size, composition and content are independent. Groups are not automatically full shots. FS requires essentially head-to-toe framing; LS emphasizes the environment. Text cards have no size. These are suggestions only; project tags remain unchanged.</p><p id="summary"></p><header><span id="count"></span> <button id="export">Export revised review</button></header><div class="grid"></div><script>
const data=DATA,refs=REFS,summary=SUMMARY;
let review={};try{review=JSON.parse(localStorage.getItem('editmap-qwen-review-v2')||'{}')}catch{}
document.querySelector('#summary').textContent=`${summary.matchesOriginalLabels}/${summary.originalScored} match the ORIGINAL labels; this is not accuracy under the revised definitions. Median request ${summary.medianSeconds.toFixed(2)}s. ${summary.uncertainCount} predictions flagged uncertain.`;
const choices={size:['ECS','CS','MS','FS','LS','Unknown','Not applicable'],composition:['Single person','Two-shot','Group','Unknown'],content:['People','Object / detail','Text / title card','Other','Unknown']};
function status(){document.querySelector('#count').textContent=`${Object.values(review).filter(r=>r.confirmed).length}/${data.results.length} confirmed under revised definitions`;try{localStorage.setItem('editmap-qwen-review-v2',JSON.stringify(review))}catch{}}
for(const r of data.results){const id=r.index;const a=document.createElement('article');const img=document.createElement('img');img.src=`shot-${id}.jpg`;img.alt=`Shot ${id}`;a.append(img);const title=document.createElement('h3');title.textContent=`Shot ${id}`;a.append(title);const p=document.createElement('p');p.textContent=`Model: ${r.prediction} / ${r.composition} / ${r.content}${r.uncertain?' / uncertain':''}. Original reference: ${refs[id]||'Unreviewed'}.`;a.append(p);
const values=review[id]||{size:r.prediction,composition:r.composition,content:r.content,uncertain:r.uncertain,confirmed:false};if(values.content==='Text / title card') values.size='Not applicable';review[id]=values;const controls={};
for(const [field,options] of Object.entries(choices)){const label=document.createElement('label');label.textContent=field;const select=document.createElement('select');select.setAttribute('aria-label',`Shot ${id} ${field}`);for(const v of options){const o=document.createElement('option');o.value=v;o.textContent=v;select.append(o)}select.value=values[field];controls[field]=select;select.onchange=()=>{const wasText=values.content==='Text / title card';values[field]=select.value;if(field==='content'&&wasText&&values.content!=='Text / title card'){values.size='Unknown';controls.size.value='Unknown';}if(values.content==='Text / title card'){values.size='Not applicable';controls.size.value=values.size;}controls.size.disabled=values.content==='Text / title card';values.confirmed=false;check.checked=false;status()};label.append(select);a.append(label)}controls.size.disabled=values.content==='Text / title card';
const u=document.createElement('label'),uncertain=document.createElement('input');uncertain.type='checkbox';uncertain.checked=values.uncertain;uncertain.onchange=()=>{values.uncertain=uncertain.checked;values.confirmed=false;check.checked=false;status()};u.append(uncertain,' Uncertain framing');a.append(u);
const l=document.createElement('label'),check=document.createElement('input');check.type='checkbox';check.checked=values.confirmed;check.onchange=()=>{values.confirmed=check.checked;status()};l.append(check,' Reviewed and confirmed');a.append(l);document.querySelector('.grid').append(a)}status();
document.querySelector('#export').onclick=()=>{const blob=new Blob([JSON.stringify({schemaVersion:2,model:data.model,prompt:data.prompt,predictions:data.results,referenceLabels:review},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='editmap-review-v2.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
</script></html>'''
(root/'review-v2.html').write_text(page.replace('DATA',json.dumps(data)).replace('REFS',json.dumps(refs)).replace('SUMMARY',json.dumps(summary)))
print(summary)
